SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(SUM(R.REVIEW_SCORE) / COUNT(*), 2) AS SCORE
FROM REST_INFO AS I
RIGHT JOIN REST_REVIEW AS R 
ON I.REST_ID = R.REST_ID
WHERE SUBSTRING(ADDRESS, 1,2) = '서울'
GROUP BY REST_ID
ORDER BY SCORE DESC, FAVORITES DESC