WITH RECURSIVE ecoliCTE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT D.ID, D.PARENT_ID, G.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA D
    JOIN ecoliCTE G
    ON D.PARENT_ID = G.ID
)
SELECT COUNT(*) AS COUNT, GENERATION
FROM ecoliCTE E
LEFT JOIN ECOLI_DATA D ON E.ID = D.PARENT_ID
WHERE D.ID IS NULL
GROUP BY GENERATION
ORDER BY GENERATION ASC;