SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT F
WHERE CATEGORY IN ('과자', '국', '김치', '식용유') AND 
    (SELECT MAX(PRICE) 
     FROM FOOD_PRODUCT D
     WHERE D.CATEGORY = F.CATEGORY
     GROUP BY CATEGORY) = PRICE
ORDER BY MAX_PRICE DESC;